### ISSUE TITLE
Link sections to the navbar

### ISSUE THREAD

**Issue by claynaut** [citrushack/cutiehack2021#23]
**Task:** Link sections (home, about, FAQ, etc.) to the navbar

- Dependent on #1 
- Currently, home and sponsor sections are on the index page so you can work on those first while the scaffolding for the other sections are being worked on
- When a user clicks on a nav link, the page scrolls down to the linked section
- Try using the react-scroll library to get this to work

**Comment by rajbirjohar** [comment]
Also dealing with #22.

**Comment by rajbirjohar** [comment]
For one page apps here is an [example](https://github.com/citrushack/Citrushack2021/blob/master/pages/index.js) of using react-scroll library. This is how we wrote our [Navigation links](https://github.com/citrushack/Citrushack2021/blob/master/components/Nav.js) so we can highlight the tabs when on each section. Notice the code:

```js
const NavigationLinks = ({ title, href }) => (
  <>
    <div className={Navstyles.navlistlink}>
      <ScrollLink
        to={href}
        spy={true}
        smooth={true}
        duration={800}
        activeClass="active"
        className="link"
      >
        {title}
      </ScrollLink>
    </div>
  </>
);
```

The classes `active` and `link` should be placed in the `globals.css` file since it does not play nicely with CSS modules.
